[book]
authors = ["Phodal Huang"]
language = "zh-cn"
multilingual = false
src = "src"
title = "软件架构：分析、治理的模式与实践"

[output.html]
git-repository-url = "https://github.com/archguard/book"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/archguard/book/edit/master/{path}"
site-url = "/"
